version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FX_FAKE: ${FX_FAKE}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE:-es}
